
limit_req_zone $binary_remote_addr zone=one:10m rate=90r/m;

# ===== production ======
# server {
#     listen 80;
#     listen [::]:80;  
#     server_name forum.anam-dev.online;

#     # To obtain ssl certificate
#     location /.well-known/acme-challenge/ {
#         root /var/www/certbot;
#     }

#     location / {
#         return 308 https://$host$request_uri;
#     }
# }

# server {
#     listen 443 ssl;
#     listen [::]:443 ssl;
#     server_name forum.anam-dev.online;

#     ssl_certificate /etc/letsencrypt/live/forum.anam-dev.online/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/forum.anam-dev.online/privkey.pem;

#     location / {
#         proxy_pass http://forum-api:3000; # forum-api are docker compose service name
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }

#     location /threads {
#         limit_req zone=one;

#         proxy_pass http://forum-api:3000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }


# ===== local development ======
server {
    listen 80;
    listen [::]:80;  
    server_name forum.anam-dev.online localhost;

    # Endpoint root API
    location / {
        proxy_pass http://forum-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Endpoint spesifik untuk threads dengan Rate Limiting
    location /threads {
        limit_req zone=one;

        proxy_pass http://forum-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}